name: iOS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
    
    - name: Build
      run: |
        xcodebuild -project attancde.xcodeproj \
                   -scheme attancde \
                   -destination 'generic/platform=iOS Simulator' \
                   clean build
    
    - name: Test
      run: |
        xcodebuild -project attancde.xcodeproj \
                   -scheme attancde \
                   -destination 'generic/platform=iOS Simulator' \
                   test